/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\mayer\\Documents\\Projects\\newallet\\merchant\\docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-f5ce275c",
    path: "/api/create_payment.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f5ce275c").then(next)
    },
  },
  {
    name: "v-36b380f4",
    path: "/api/delete_payment.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36b380f4").then(next)
    },
  },
  {
    name: "v-c6b0ed64",
    path: "/api/callback.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c6b0ed64").then(next)
    },
  },
  {
    name: "v-3b6a88d4",
    path: "/api/get_payment.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b6a88d4").then(next)
    },
  },
  {
    name: "v-3e512222",
    path: "/api/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e512222").then(next)
    },
  },
  {
    path: "/api/index.html",
    redirect: "/api/"
  },
  {
    name: "v-203c045e",
    path: "/api/sign.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-203c045e").then(next)
    },
  },
  {
    name: "v-8e4b0c48",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8e4b0c48").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-2f3d5e4f",
    path: "/modules/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f3d5e4f").then(next)
    },
  },
  {
    path: "/modules/index.html",
    redirect: "/modules/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]